# Experimentation Workflow Configuration

# LLM model settings
model:
  name: "claude-3-5-sonnet-20241022"  # Default model
  temperature: 0.2  # Lower temperature for more deterministic code generation
  max_tokens: 8000

# Experiment parameters
experiment:
  max_iterations: 5  # Maximum number of experimental iterations
  max_reflections: 3  # Maximum number of reflections per iteration
  timeout: 7200  # Maximum time for an experiment in seconds (2 hours)
  
# Resources
resources:
  gpus: "auto"  # Auto-detect available GPUs, or specify list like [0, 1]
  cpu_cores: 4
  memory_limit: "16GB"

# Output settings
output:
  experiment_dir: "../../experiments/{template_name}/{idea_id}/"
  log_path: "../../logs/experiments/{template_name}/"
  save_all_iterations: true
  
# Code execution settings
execution:
  sandbox: true  # Run in a sandboxed environment
  timeout_per_execution: 1800  # 30 minutes per execution
  allow_network: false  # Restrict network access during execution

# Templates
templates:
  base_path: "../../../templates/"
  available:
    - "nanoGPT"
    - "nanoGPT_lite"
    - "2d_diffusion"
    - "grokking"
    - "custom" 