python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title adaptive_dual_scale_denoising --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title data_augmentation_grokking --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title dual_expert_denoiser --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title gan_diffusion --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title grid_based_noise_adaptation --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title layerwise_lr_grokking --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title mdl_grokking_correlation --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title multi_style_adapter --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title rl_lr_adaptation --improvement --example-papers-dir example_papers_for_exp2
python launch_scientist_exp2_v2.py --model "deepseek/deepseek-chat" --old-paper-title weight_initialization_grokking --improvement --example-papers-dir example_papers_for_exp2