# Idea Generation Workflow Configuration

# LLM model settings
model:
  name: "claude-3-5-sonnet-20241022"  # Default model
  temperature: 0.7
  max_tokens: 4000

# Idea generation parameters
generation:
  num_ideas: 5  # Number of ideas to generate per run
  domain: "nanoGPT"  # Default domain/template
  creativity_level: "high"  # Can be low, medium, high
  
# Novelty check settings
novelty_check:
  enabled: true
  search_engine: "semantic_scholar"  # Can be semantic_scholar or openalex
  similarity_threshold: 0.8  # Ideas with similarity above this threshold are considered not novel

# Output settings
output:
  format: "json"
  save_path: "../../results/novelty/"
  log_path: "../../logs/idea_generation/"

# Prompt customization
prompts:
  idea_template_path: "../../../ai_scientist/fewshot_examples/idea_generation.txt"
  novelty_template_path: "../../../ai_scientist/fewshot_examples/novelty_check.txt" 