# Paper Writing Workflow Configuration

# LLM model settings
model:
  name: "claude-3-5-sonnet-20241022"  # Default model
  temperature: 0.5
  max_tokens: 16000

# Paper generation parameters
paper:
  sections:
    - "Abstract"
    - "Introduction"
    - "Related Work"
    - "Method"
    - "Experiments"
    - "Results"
    - "Discussion"
    - "Conclusion"
    - "References"
  max_length: 12  # Target maximum page length
  style: "academic"  # Writing style
  
# LaTeX settings
latex:
  template_path: "../../config/templates/paper_template.tex"
  bibliography_style: "unsrt"
  compile_pdf: true
  timeout: 300  # Timeout for LaTeX compilation in seconds

# Figure generation
figures:
  include_plots: true
  max_figures: 8
  dpi: 300
  format: "pdf"

# Output settings
output:
  draft_dir: "../../papers/drafts/{idea_id}/"
  final_dir: "../../papers/final/{idea_id}/"
  assets_dir: "../../papers/assets/{idea_id}/"
  log_path: "../../logs/paper_writing/{idea_id}/"
  
# Review settings
review:
  enabled: true
  review_output: "../../reviews/{idea_id}/"
  improvement_iterations: 2  # Number of improvement iterations after review 